function createIngestTools(deps) {
  const {
    fs,
    path,
    fail,
    relativeTo,
    parseFrontmatter,
    stripFrontmatter,
    isZhWikiRoot,
    ensureDir,
    quoteYaml,
    sanitizeTitleFragment,
    findIndexPage,
    extractTextSummary,
    detectSchemaVersion,
    resolvePageKindLayer,
    resolveDomains,
    getEvidenceDir,
    getAtomDir,
    getChangelogPath
  } = deps;

  function uniquePath(filePath) {
    if (!fs.existsSync(filePath)) return filePath;
    const parsed = path.parse(filePath);
    let counter = 2;
    while (true) {
      const candidate = path.join(parsed.dir, `${parsed.name} ${counter}${parsed.ext}`);
      if (!fs.existsSync(candidate)) return candidate;
      counter += 1;
    }
  }

  function decodeHtmlEntities(value) {
    return value
      .replace(/&nbsp;/g, " ")
      .replace(/&amp;/g, "&")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'");
  }

  function extractMetaContent(content, name) {
    const patterns = [
      new RegExp(`<meta[^>]+property=["']${name}["'][^>]+content=["']([^"']+)["'][^>]*>`, "i"),
      new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+property=["']${name}["'][^>]*>`, "i"),
      new RegExp(`<meta[^>]+name=["']${name}["'][^>]+content=["']([^"']+)["'][^>]*>`, "i"),
      new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+name=["']${name}["'][^>]*>`, "i")
    ];
    for (const pattern of patterns) {
      const match = content.match(pattern);
      if (match?.[1]) {
        return decodeHtmlEntities(match[1].trim());
      }
    }
    return "";
  }

  function extractTitleFromMarkdown(content, fallback) {
    const frontmatter = parseFrontmatter(content);
    if (frontmatter?.title) {
      return String(frontmatter.title).replace(/^["']|["']$/g, "").trim();
    }
    const heading = content.match(/^#\s+(.+)$/m);
    if (heading) return heading[1].trim();
    return fallback;
  }

  function extractTitleFromHtml(content, fallback) {
    const match = content.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
    if (!match) return fallback;
    return decodeHtmlEntities(match[1].replace(/<[^>]+>/g, "").trim()) || fallback;
  }

  function extractReadableHtmlText(content) {
    const container =
      content.match(/<article[^>]*>([\s\S]*?)<\/article>/i)?.[1] ||
      content.match(/<main[^>]*>([\s\S]*?)<\/main>/i)?.[1] ||
      content.match(/<body[^>]*>([\s\S]*?)<\/body>/i)?.[1] ||
      content;

    return decodeHtmlEntities(
      container
        .replace(/<script[\s\S]*?<\/script>/gi, "")
        .replace(/<style[\s\S]*?<\/style>/gi, "")
        .replace(/<noscript[\s\S]*?<\/noscript>/gi, "")
        .replace(/<svg[\s\S]*?<\/svg>/gi, "")
        .replace(/<(nav|header|footer|aside|form)[^>]*>[\s\S]*?<\/\1>/gi, "")
        .replace(/<\/li>/gi, "\n")
        .replace(/<li[^>]*>/gi, "- ")
        .replace(/<\/h1>/gi, "\n")
        .replace(/<h1[^>]*>/gi, "# ")
        .replace(/<\/h2>/gi, "\n")
        .replace(/<h2[^>]*>/gi, "## ")
        .replace(/<\/h3>/gi, "\n")
        .replace(/<h3[^>]*>/gi, "### ")
        .replace(/<\/(p|div|section|article|li|h[1-6]|br)>/gi, "\n")
        .replace(/<[^>]+>/g, " ")
        .replace(/[ \t]+\n/g, "\n")
        .replace(/\n[ \t]+/g, "\n")
        .replace(/\n{3,}/g, "\n\n")
        .trim()
    );
  }

  function extractMarkdownSummary(content) {
    const body = stripFrontmatter(content);
    const lines = body
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean)
      .filter((line) => !line.startsWith("---") && !line.startsWith("#"));
    return lines[0] || "";
  }

  function detectMedia(target, isUrl) {
    if (!isUrl) return "article";
    const lower = target.toLowerCase();
    if (lower.includes("youtube.com") || lower.includes("youtu.be") || lower.includes("bilibili.com")) {
      return "video";
    }
    return "article";
  }

  function normalizeDomainName(domain) {
    return domain.trim().replace(/[\\/:*?"<>|]/g, "-");
  }

  function chooseRawSubdir(root, kind, domain) {
    if (domain) return normalizeDomainName(domain);
    if (kind === "url") {
      return isZhWikiRoot(root) ? "网页" : "web";
    }
    return isZhWikiRoot(root) ? "导入" : "imported";
  }

  function buildSourcePage(root, meta, schema) {
    const zh = isZhWikiRoot(root);
    const now = new Date().toISOString().slice(0, 10);
    const summaryPrefix = zh ? "资料摘要" : "Summary";
    const pageTitle = `${summaryPrefix}：${meta.title}`;
    const sourceLabel = zh ? "来源文件" : "Source file";
    const sourceUrlLine = meta.sourceUrl
      ? zh
        ? `来源链接：${meta.sourceUrl}`
        : `Source URL: ${meta.sourceUrl}`
      : zh
        ? "来源链接："
        : "Source URL: ";
    const blockquote = zh
      ? "> ⚠️ 由 CLI 自动生成的证据层草稿。请补全核心要点、详细笔记和引用。核心观点应提炼为 atom，再整合为稳定知识页。"
      : "> ⚠️ Draft evidence-layer summary generated by CLI. Fill in key takeaways, notes, and citations. Core ideas should be distilled into atoms, then integrated into stable knowledge pages.";
    const headings = zh
      ? ["## 核心要点", "## 详细笔记", "## 引用与数据", "## 可提炼的 atom 候选", "## 晋升建议", "## 相关"]
      : ["## Key Takeaways", "## Detailed Notes", "## Quotes & Data", "## Atom Candidates", "## Promotion Hints", "## Related"];
    const draftLine = meta.summary || (zh ? "摘要待补全。" : "Summary pending refinement.");
    const rawLine = zh ? `${sourceLabel}：\`${meta.rawRelativePath}\`` : `${sourceLabel}: \`${meta.rawRelativePath}\``;
    const domainLine = zh ? `领域：${meta.domain || ""}` : `Domain: ${meta.domain || ""}`;
    const kindLine = zh ? `来源类型：${meta.sourceKind}` : `Source kind: ${meta.sourceKind}`;
    const fetchedLine = zh ? `抓取时间：${meta.fetchedAt || ""}` : `Fetched at: ${meta.fetchedAt || ""}`;

    const frontmatter = schema === "v2"
      ? `---
title: ${quoteYaml(pageTitle)}
kind: source
layer: evidence
domains: [${quoteYaml(meta.domain || "")}]
status: draft
tags: []
created: ${now}
updated: ${now}
sources: []
stability: volatile
bloom: remember
review_cycle: monthly
confidence: low
summary: ${quoteYaml(draftLine)}
source_url: ${quoteYaml(meta.sourceUrl || "")}
media: ${meta.media}
raw_path: ${quoteYaml(meta.rawRelativePath)}
source_kind: ${quoteYaml(meta.sourceKind)}
fetched_at: ${quoteYaml(meta.fetchedAt || "")}
---`
      : `---
title: ${quoteYaml(pageTitle)}
type: source
status: draft
tags: []
created: ${now}
updated: ${now}
sources: []
domain: ${quoteYaml(meta.domain || "")}
confidence: low
summary: ${quoteYaml(draftLine)}
source_url: ${quoteYaml(meta.sourceUrl || "")}
media: ${meta.media}
raw_path: ${quoteYaml(meta.rawRelativePath)}
source_kind: ${quoteYaml(meta.sourceKind)}
fetched_at: ${quoteYaml(meta.fetchedAt || "")}
---`;

    return {
      title: pageTitle,
      content: `${frontmatter}

${blockquote}

${headings[0]}

- TBD

${headings[1]}

${rawLine}
${zh ? "\n" : "\n\n"}${domainLine}

${sourceUrlLine}

${kindLine}

${fetchedLine}

${headings[2]}

- TBD

${headings[3]}

- TBD

${headings[4]}

- TBD

${headings[5]}

- [[${path.basename(findIndexPage(root), ".md")}]]
`
    };
  }

  function buildAtomPage(root, meta, index, schema) {
    const zh = isZhWikiRoot(root);
    const now = new Date().toISOString().slice(0, 10);
    const atomPrefix = zh ? "原子卡" : "Atom";
    const atomTitle = `${atomPrefix}：${meta.title} ${index + 1}`;

    const frontmatter = schema === "v2"
      ? `---
title: ${quoteYaml(atomTitle)}
kind: atom
layer: working
domains: [${quoteYaml(meta.domain || "")}]
status: seed
tags: []
aliases: []
created: ${now}
updated: ${now}
sources:
  - "[[${meta.sourceTitle}]]"
confidence: low
summary: ""
---`
      : `---
title: ${quoteYaml(atomTitle)}
type: atom
status: seed
tags: []
aliases: []
created: ${now}
updated: ${now}
sources:
  - "[[${meta.sourceTitle}]]"
confidence: low
summary: ""
---`;

    const blockquote = zh
      ? "> 从 source 提炼的原子知识草稿。待后续核实、关联、整合。"
      : "> Atomic knowledge draft distilled from source. Awaiting verification, linking, and integration.";

    return {
      title: atomTitle,
      content: `${frontmatter}

${blockquote}

## Core Idea

- TBD

## Source

- [[${meta.sourceTitle}]]

## Next Steps

- [ ] Verify key claims
- [ ] Link to existing concepts/topics
- [ ] Integrate into a stable knowledge page
`
    };
  }

  function appendChangelogEntry(root, title, rawRelativePath, summaryRelativePath, atomPaths, schema) {
    const zh = isZhWikiRoot(root);
    const changelogPath = getChangelogPath(root, schema);
    if (!fs.existsSync(changelogPath)) return;
    const date = new Date().toISOString().slice(0, 10);
    const atomList = atomPaths.length
      ? atomPaths.map((p) => `- ${p}`).join("\n")
      : (zh ? "- 无" : "- None");
    const entry = zh
      ? `\n## [${date}] ingest | ${title}\n- 来源：${rawRelativePath}\n- 新建 source 页：${summaryRelativePath}\n- 新建 atom 草稿：\n${atomList}\n`
      : `\n## [${date}] ingest | ${title}\n- Source: ${rawRelativePath}\n- New source page: ${summaryRelativePath}\n- New atom drafts:\n${atomList}\n`;
    fs.appendFileSync(changelogPath, entry, "utf8");
  }

  async function runIngest(root, rawArgs) {
    let domain = "";
    const rest = [];

    for (let i = 0; i < rawArgs.length; i += 1) {
      const arg = rawArgs[i];
      if (arg === "--domain") {
        const next = rawArgs[i + 1];
        if (!next) fail("missing value for --domain");
        domain = next;
        i += 1;
        continue;
      }
      rest.push(arg);
    }

    const target = rest[0];
    if (!target) {
      fail("ingest requires a local markdown file path or a URL");
    }

    const schema = detectSchemaVersion(root);
    const isUrl = /^https?:\/\//i.test(target);
    const rawSubdir = chooseRawSubdir(root, isUrl ? "url" : "file", domain);
    const rawDir = path.join(root, "raw", rawSubdir);
    const evidenceDir = getEvidenceDir(root, schema);
    ensureDir(rawDir);
    ensureDir(evidenceDir);

    let title = "";
    let rawPath = "";
    let rawContent = "";
    let sourceUrl = "";
    let media = detectMedia(target, isUrl);
    let sourceKind = isUrl ? "url" : "file";
    let fetchedAt = "";
    let extractedSummary = "";

    if (isUrl) {
      const response = await fetch(target);
      if (!response.ok) {
        fail(`failed to fetch URL: ${response.status} ${response.statusText}`);
      }
      const responseText = await response.text();
      const url = new URL(target);
      title = sanitizeTitleFragment(
        extractTitleFromHtml(responseText, url.pathname.split("/").filter(Boolean).pop() || url.hostname)
      );
      extractedSummary =
        extractMetaContent(responseText, "og:description") ||
        extractMetaContent(responseText, "twitter:description") ||
        extractMetaContent(responseText, "description");
      const readableText = extractReadableHtmlText(responseText);
      if (!extractedSummary) {
        extractedSummary = extractTextSummary(readableText, title);
      }
      fetchedAt = new Date().toISOString();
      rawContent = `# ${title}

Source URL: ${target}

Fetched at: ${fetchedAt}

## Extracted Content

${readableText}
`;
      rawPath = uniquePath(path.join(rawDir, `${title}.md`));
      sourceUrl = target;
    } else {
      const inputPath = path.resolve(target);
      if (!fs.existsSync(inputPath)) {
        fail(`input file not found: ${inputPath}`);
      }
      if (path.extname(inputPath).toLowerCase() !== ".md") {
        fail("ingest currently supports local markdown files only");
      }
      rawContent = fs.readFileSync(inputPath, "utf8");
      title = sanitizeTitleFragment(extractTitleFromMarkdown(rawContent, path.basename(inputPath, ".md")));
      extractedSummary = extractMarkdownSummary(rawContent);
      const insideRoot = !path.relative(path.join(root, "raw"), inputPath).startsWith("..");
      rawPath = insideRoot ? inputPath : uniquePath(path.join(rawDir, `${title}.md`));
      sourceKind = "file";
      if (!insideRoot) {
        fs.writeFileSync(rawPath, rawContent, "utf8");
      }
    }

    if (isUrl) {
      fs.writeFileSync(rawPath, rawContent, "utf8");
    }

    const rawRelativePath = relativeTo(root, rawPath);
    const sourcePage = buildSourcePage(root, {
      title,
      rawRelativePath,
      sourceUrl,
      media,
      sourceKind,
      fetchedAt,
      domain: normalizeDomainName(domain || ""),
      summary: extractedSummary
    }, schema);
    const summaryPath = uniquePath(path.join(evidenceDir, `${sourcePage.title}.md`));
    fs.writeFileSync(summaryPath, sourcePage.content, "utf8");

    // Generate atom drafts (v2 only)
    const atomPaths = [];
    if (schema === "v2") {
      const atomDir = getAtomDir(root, domain, schema);
      if (atomDir) {
        ensureDir(atomDir);
        const atomCount = Math.min(3, Math.max(1, Math.floor(extractedSummary.length / 40) + 1));
        for (let i = 0; i < atomCount; i += 1) {
          const atomPage = buildAtomPage(root, {
            title,
            domain: normalizeDomainName(domain || ""),
            sourceTitle: sourcePage.title
          }, i, schema);
          const atomPath = uniquePath(path.join(atomDir, `${atomPage.title}.md`));
          fs.writeFileSync(atomPath, atomPage.content, "utf8");
          atomPaths.push(relativeTo(root, atomPath));
        }
      }
    }

    appendChangelogEntry(root, title, rawRelativePath, relativeTo(root, summaryPath), atomPaths, schema);

    console.log(`[ingest] root: ${root}`);
    console.log(`schema: ${schema}`);
    console.log(`source kind: ${sourceKind}`);
    console.log(`raw file: ${rawRelativePath}`);
    console.log(`source page: ${relativeTo(root, summaryPath)}`);
    if (atomPaths.length > 0) {
      console.log(`atom drafts: ${atomPaths.length}`);
      for (const atomPath of atomPaths) {
        console.log(`  - ${atomPath}`);
      }
    }
    if (sourceUrl) {
      console.log(`source url: ${sourceUrl}`);
    }
  }

  return { runIngest };
}

module.exports = { createIngestTools };
